name:                bababu
version:             0.1.0.0
github:              "githubuser/bababu"
license:             BSD3
author:              "Zale Yu"
maintainer:          "zale.yu@gmail.com"
copyright:           "2019 Zale"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thiross/bababu#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- free
- mtl
- tagsoup

library:
  source-dirs: src

executables:
  bababu:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bababu

tests:
  bababu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bababu
